### PR TITLE
Autodetect ROLE_NAME in test Vagrantfile from role dirname

### PR DESCRIPTION
**Pull request by trinitronx**
You might be wondering why I'm making this change... The reason is because I'm trying
to test a role which depends on this one using [`test-kitchen`][3] and [`kitchen-ansible`][1].
The role dependency tool [`librarian-ansible`][2] uses the Ruby Net::SCP class to copy
role files into the Vagrant VMs that Test Kitchen starts up.  The problem is that since the
'tests/roles/tftp' directory was a symbolic link to a parent dir, Net::SCP was giving an infinite
recursion error when it tried to copy the contents of that symbolic link's target.

The error looked like this:

    Transferring files to <dev-centos-70>
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: Failed to complete #converge action: [Too many levels of symbolic links @ rb_file_s_stat - /var/folders/_8/fv9hxvf177jcm22v_m913398b80c28/T/dev-centos-70-sandbox-20150618-62737-19y99mq/roles/bertvv.tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp/tests/roles/tftp]
    >>>>>> ----------------------
    >>>>>> Please see .kitchen/logs/kitchen.log for more details
    >>>>>> Also try running `kitchen diagnose --all` for configuration

[1]: https://github.com/neillturner/kitchen-ansible
[2]: https://github.com/bcoe/librarian-ansible
[3]: https://github.com/test-kitchen/test-kitchen

### CODE REVIEW

**Comment by bertvv** [comment]
Thank you for this contribution and for your interest.

Sorry for not replying earlier. Reason is: I have thought a lot about this PR, and was in doubt of whether I should merge it. In the end, I decided not to.

It is my sincere opinion (and [not only mine](https://groups.google.com/d/msg/ansible-project/TawjChwaV08/3p6Zv24rMWgJ)) that librarian-ansible is not a good way to do role dependency management for Ansible. It is written in Ruby, which is not a good fit for Ansible. Additionally, Ansible [has its own dependency management](http://docs.ansible.com/galaxy.html#advanced-control-over-role-requirements-files) tool, `ansible-galaxy` so it should be preferred over an external tool. The same goes for test-kitchen: I'm not sure what it brings to the table that cannot be realised using a test playbook or a less dependency-heavy framework.

The code for the system test as it is now is as simple as possible and self-contained, I would prefer it to stay that way. Moving everything to *Ruby* templates seems a bridge too far to me. For integration tests, I think you should not use this code but write your own fixture. If test-kitchen allows this, don't copy the test/ directory at all. 

Feel free, though, to maintain your own fork. I don't have any new features planned, and any changes won't affect your code much.

**Comment by trinitronx** [comment]
@bertvv:  First of all, my apologies for not responding sooner!  (Other work responsibilities & life beckoned me away when I first saw this GitHub inbox item, and later I couldn't find it as it was marked as read)

The real issue I was running into here was due to the symbolic link preventing a role which depended on this one from being tested with the tools I was using at the time.  The symlink caused an infinite copy recursion bug in `librarian-ansible`.  I was trying to preserve your preference to use a test playbook + Vagrant (both of these are valid methods for testing too), while trying to workaround the bug by avoiding the symlink.  Sorry if it wasn't what you preferred to do, it appears that our individual preferences in testing tools had somehow collided in an unexpected way.  I've not seen many Ansible roles in the community with a focus on testing, and am happy to see that you're actually doing it!  (Really this is a huge issue with some roles on Ansible Galaxy, especially with roles that claim to support multiple platforms, but don't work).  If you haven't tried `test-kitchen` or `kitchen-ansible` yet, I'd encourage you check them out and see what you think.  They're great tools which have been gaining some good traction in the community (`test-kitchen` especially has been well tested against multiple platforms in the Chef community, but also works with other provisioners via gem plugins like `kitchen-puppet` and `kitchen-ansible`).  I've found them particularly useful when testing roles across different platforms & versions of an OS.  I've got a demo / research repo for how to install & use it here: [trinitronx/ansible-tdd][ansible-tdd].

I can see that there is some pushback in the community about the `librarian-ansible` project... mainly because of misunderstandings about how to use it, that it's in Ruby (and it appears that Ansible folks are generally more comfortable with Python) and the way it works<sup><a href="#subscript1">&lbrack;1&rbrack;</a></sup> due to how it's been modeled after [`librarian-chef`][1] and is similar to [`Bundler`][2] / [`Berkshelf`][3].  That's fine, it's simply a preference of what tool & language you like.  I'm not too set on using `librarian-ansible` myself, however at the time I wrote my test-kitchen tests for a role which depended on this one, it was the only tool which was integrated with [`kitchen-ansible`][kitchen-ansible].  I'll be honest and say that when working with Chef, I didn't necessarily prefer the [`librarian`-style][4] tools, but rather Bundler / Berkshelf, but that's just a result of my previous experience with using those tools and having prior experience with Chef & Ruby.  Again, just personal preference, and not a big deal.  Sorry if it seemed I was trying to force these tools or way of working down your throat in any way, they're just tools that I've found especially useful myself when developing config management scripts & automation (whether playbooks or cookbooks).

I'm not sure I agree with [Michael DeHaan's point][5] about the ["tragedy of the commons" effect][6] of having multiple tools.  It appears that this term is generally associated with the depletion of some finite resource, which necessarily doesn't apply in the context of using software tools.  (It's all just bits, and there's not really a shortage in this instance).  I suppose one could argue that the real finite resource is the attention & time that the community has to focus on projects & learning new tools.  I think we can agree that having hundreds of tools for the same thing probably doesn't serve us well in the community in that respect.  However, having a couple probably isn't a bad idea.  When one fails or doesn't work, try the other (I had this experience flipping back and forth between `librarian-chef` and `berkshelf`at various points during their development, and found that it was useful to have a fallback tool to get the job done).

Since `ansible-galaxy`has the ability to checkout git repos, and has the general popular support of the community due to DeHaan's blessing, then I'm all for using that (as long as it solves the practical problems thrown at it and doesn't fail or break often).  I hadn't had much need for using `ansible-galaxy` and felt it was somewhat lacking in being able to specify version constraints due to the lack of versioning in ansible community roles.  Version constraints and version locking are important when code changes over time (often in unpredictable or breaking ways).  This is the reason for tools like Bundler, and yes: config management is a declarative language or form of "code", so should be treated like versioned software too.

Now that [`kitchen-ansible`][7] [supports using `ansible-galaxy` to download role dependencies][8], I'm happy to try refactoring towards using that.  Perhaps it will avoid this infinite recursion copy issue.

<sub><a name="subscript1"></a> &lbrack;1&rbrack; Librarian-based tools control a specific directory structure's contents, overwriting local changes.  This is similar to the Chef Repo pattern (and Python & Perl patterns) of having a `site-cookbooks` directory for site-specific (i.e.: "local", private) things, and a `cookbooks` directory for upstream / community dependencies.  Python and Perl use a similar pattern where `site-things` (i.e.: `site-packages`) is used for "local" stuff, and another dir is used for official / upstream stuff (i.e.: `/usr/lib/python2.7/`).  The intent for usage is that the tool is mainly for tracking & importing upstream community code, which should generally be committed back to with Pull Requests for changes to "stick" and be re-imported.  If making local changes which one does not wish to share, a fork is more appropriate, or a completely homegrown private solution would be to just add the code into your Ansible playbooks repo under a different `site-roles` path (e.g.: [using roles_path as a search path][7]).  In the case of open source community roles, the user is supposed to add either their forked repo to their Ansiblefile, or push changes back upstream & use the original project.  The tool doesn't prevent this, but merely enables the open source community's way of working via forks & pull requests.  Bundler & Berkshelf allow the same workflow, but you must "vendor" or use `--path` to explicitly install your upstream dependencies to a specific directory.</sub>

[1]: https://github.com/applicationsonline/librarian-chef
[2]: http://bundler.io
[3]: http://berkshelf.com/
[4]: https://github.com/applicationsonline/librarian
[5]: https://groups.google.com/d/msg/ansible-project/TawjChwaV08/3p6Zv24rMWgJ
[6]: https://en.wikipedia.org/wiki/Tragedy_of_the_commons
[7]: http://docs.ansible.com/ansible/intro_configuration.html#roles-path
[8]: https://github.com/neillturner/kitchen-ansible/pull/18
[ansible-tdd]: @bertvv:  First of all, my apologies for not responding sooner!  (Other work responsibilities & life beckoned me away when I first saw this GitHub inbox item)

The real issue I was running into here was due to the symbolic link preventing a role which depended on this one from being tested with the tools I was using at the time.  The symlink caused an infinite copy recursion bug in `librarian-ansible`.  I was trying to preserve your preference to use a test playbook + Vagrant (both of these are valid methods for testing too), while trying to workaround the bug by avoiding the symlink.  Sorry if it wasn't what you preferred to do, it appears that our individual preferences in testing tools had somehow collided in an unexpected way.  I've not seen many Ansible roles in the community with a focus on testing, and am happy to see that you're actually doing it!  (Really this is a huge issue with some roles on Ansible Galaxy, especially with roles that claim to support multiple platforms, but don't work).  If you haven't tried `test-kitchen` or `kitchen-ansible` yet, I'd encourage you check them out and see what you think.  They're great tools which have been gaining some good traction in the community (`test-kitchen` especially has been well tested against multiple platforms in the Chef community, but also works with other provisioners via gem plugins like `kitchen-puppet` and `kitchen-ansible`).  I've found them particularly useful when testing roles across different platforms & versions of an OS.  I've got a demo / research repo for how to install & use it here: trinitronx/ansible-tdd

I can see that there is some pushback in the community about the `librarian-ansible` project... mainly because of misunderstandings about how to use it, that it's in Ruby (and it appears that Ansible folks are generally more comfortable with Python) and the way it works<sup><a href="#subscript1">&lbrack;1&rbrack;</a></sup> due to how it's been modeled after [`librarian-chef`][1] and is similar to [`Bundler`][2] / [`Berkshelf`][3].  That's fine, it's simply a preference of what tool & language you like.  I'm not too set on using `librarian-ansible` myself, however at the time I wrote my test-kitchen tests for a role which depended on this one, it was the only tool which was integrated with [`kitchen-ansible`][kitchen-ansible].  I'll be honest and say that when working with Chef, I didn't necessarily prefer the [`librarian`-style][4] tools, but rather Bundler / Berkshelf, but that's just a result of my previous experience with using those tools and having prior experience with Chef & Ruby.  Again, just personal preference, and not a big deal.  Sorry if it seemed I was trying to force these tools or way of working down your throat in any way, they're just tools that I've found especially useful myself when developing config management scripts & automation (whether playbooks or cookbooks).

I'm not sure I agree with [Michael DeHaan's point][5] about the ["tragedy of the commons" effect][6] of having multiple tools.  It appears that this term is generally associated with the depletion of some finite resource, which necessarily doesn't apply in the context of using software tools.  (It's all just bits, and there's not really a shortage in this instance).  I suppose one could argue that the real finite resource is the attention & time that the community has to focus on projects & learning new tools.  I think we can agree that having hundreds of tools for the same thing probably doesn't serve us well in the community in that respect.  However, having a couple probably isn't a bad idea.  When one fails or doesn't work, try the other (I had this experience flipping back and forth between `librarian-chef` and `berkshelf`at various points during their development, and found that it was useful to have a fallback tool to get the job done).

Since `ansible-galaxy` now has the ability to checkout git repos, and has the general popular support of the community due to DeHaan's blessing, then I'm all for using that (as long as it solves the practical problems thrown at it and doesn't fail or break often).  I hadn't had much need for using `ansible-galaxy` and felt it was somewhat lacking in being able to specify version constraints due to the lack of versioning in ansible community roles.  In my past experience with Chef, version constraints and version locking are important when code changes over time (often in unpredictable or breaking ways).  This is the reason for tools like Bundler, and yes: config management is a declarative language or form of "code", so should be treated like versioned software too.

Now that [`kitchen-ansible`][7] [supports using `ansible-galaxy` to download role dependencies][8], I'm happy to try refactoring towards using that.  Perhaps it will avoid this infinite recursion copy issue.

<sub><a name="subscript1"></a> &lbrack;1&rbrack; Librarian-based tools control a specific directory structure's contents, overwriting local changes.  This is similar to the Chef Repo pattern (and Python & Perl patterns) of having a `site-cookbooks` directory for site-specific (i.e.: "local", private) things, and a `cookbooks` directory for upstream / community dependencies.  Python and Perl use a similar pattern where `site-things` (i.e.: `site-packages`) is used for "local" stuff, and another dir is used for official / upstream stuff (i.e.: `/usr/lib/python2.7/`).  The intent for usage is that the tool is mainly for tracking & importing upstream community code, which should generally be committed back to with Pull Requests for changes to "stick" and be re-imported.  If making local changes which one does not wish to share, a fork is more appropriate, or a completely homegrown private solution would be to just add the code into your Ansible playbooks repo under a different `site-roles` path (e.g.: [using roles_path as a search path][7]).  In the case of open source community roles, the user is supposed to add either their forked repo to their Ansiblefile, or push changes back upstream & use the original project.  The tool doesn't prevent this, but merely enables the open source community's way of working via forks & pull requests.  Bundler & Berkshelf allow the same workflow, but you must "vendor" or use `--path` to explicitly install your upstream dependencies to a specific directory.</sub>

[1]: https://github.com/applicationsonline/librarian-chef
[2]: http://bundler.io
[3]: http://berkshelf.com/
[4]: https://github.com/applicationsonline/librarian
[5]: https://groups.google.com/d/msg/ansible-project/TawjChwaV08/3p6Zv24rMWgJ
[6]: https://en.wikipedia.org/wiki/Tragedy_of_the_commons
[7]: http://docs.ansible.com/ansible/intro_configuration.html#roles-path
[8]: https://github.com/neillturner/kitchen-ansible/pull/18
[kitchen-ansible]: https://github.com/trinitronx/ansible-tdd
[kitchen-ansible]: https://github.com/neillturner/kitchen-ansible/

**Comment by bertvv** [comment]
Hi James,

I really appreciate you took the time for writing this extensive reply. Testing infrastructure is a relatively new topic and it seems everyone is still looking for the best way to approach this. I certainly don't have all the answers, so I value your insights. I really did not have the feeling that you were pushing something down my throat, on the contrary.

Your mail triggered me to think about another solution, and I think I have one. I think your proposal is actually quite clever, but it makes the code more complex than I'm comfortable with. But the way my roles are structured now is definitely not ideal. I never felt quite comfortable with the fact that my test code is installed with the role and the symbolic link is -let's admit it- a hack.

So what I was thinking is to separate the test code in another branch. It would have the benefit that when you pull the master branch or a specific version from your own test environment, you don't get my test code, nor the problematic link. My test branch would only contain what is now in the `tests/` directory and I can script pulling the master branch, and run `vagrant up` to execute the tests. How does that sound?


I agree wholeheartedly with you that too many roles that are published on Galaxy lack testing. Sometimes there is a test, but none of the role variables are assigned, so only the default values are tested.

I also agree that it's a good thing that there is choice in test tools. One should be able to experiment with several ways to solve the testing problem, applying different approaches and selecting what's best suited for a particular environment. Diversity is the best way to discover and develop best practices. If I have some time, I'll check out `test-kitchen`. Thank you for the recommendation!

It seems that, now at least, `ansible-galaxy` does allow to specify version constraints, but frankly, I haven't really needed it yet as I'm still building my "collection" of roles and I only have a limited number of production servers to maintain. So I haven't been bitten by any shortcomings in `ansible-galaxy`'s dependency management.

Anyway, I'll see if I can implement my proposal one of the following days. Or I wouldn't mind scheduling a Hangout or something sometime to discuss this and work out a good solution. And maybe chat some more about testing...

Thanks again for your insights!

bert

**Comment by trinitronx** [comment]
@bertvv: Thanks for the thoughtful reply and proposal for an innovative solution!  The alternate `test` branch sounds like a great idea if you're willing to manage the git branches & merging.  The symlinked `roles` directory is a clever hack, and we end up using it extensively in my company's own Ansible repo for playbooks.  One supported workflow is generally to run playbooks from the directory that contains them, so we end up having to have a directory structure like this:

```
ansible-playbooks
├── ansible.cfg
├── docs
├── inventory
│   ├── ec2.ini
│   ├── ec2.py
│   ├── group_vars
│   ├── host_vars
│   └── hosts
├── playbooks
│   ├── foo
│   │   ├── README.md
│   │   ├── inventory -> ../../inventory
│   │   ├── roles -> ../../roles
│   │   ├── foo.yml
│   │   ├── foo-play2.yml
│   │   ├── vars
│   │   ├── files
│   │   └── templates
│   └── bar
│       ├── README.md
│       ├── inventory -> ../../inventory
│       ├── roles -> ../../roles
│       ├── bar.yml
│       ├── vars
│       ├── files
│       └── templates
└── roles
```

Notice the symlinks for `roles` which point up to the main roles dir: `../../roles`
Luckily, we haven't run into any other recursion issues with `ansible-playbook` or other tools we use so far in this use case.

I thought your use of this hack was clever, and it was great to see a "test fixture" of the role under test built in a clever way with playbooks to wrap & test the role with Vagrant.

I'm curious how `ansible-galaxy` implements version constraints when specifying roles to install from galaxy.ansible.com.  It's not immediately apparent when I login to Ansible Galaxy how to version a role released there.  I suppose git tags or refs are probably the way to version things explicitly when importing a role from GitHub in the [requirements file][1].  However, I did run into an issue when trying to specify a non-master branch.  It appears that this is a known issue with `ansible-galaxy`.  Alas, the same scenario I had before with `librarian-chef` or `berkshelf` where the dependency management tools were both broken in some way :laughing:.  I guess this is the nature of software over time ;-)

[1]: http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file

**Comment by bertvv** [comment]
It's been a while, but I haven't forgotten about this issue...

In the master branch, the test code is now gone and put into a separate branch. The README contains instructions on how to run the tests. I use [git-worktree](https://git-scm.com/docs/git-worktree) for this, a feature I discovered only today.

I'll release a new version based on these changes shortly, and start to apply this solution my other roles.

**Pull request closed without merging**
